name: FeedBot
on:
  workflow_dispatch:
jobs:
  rss-to-mastodon:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())

      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/mastofeedbot
          key: feed-cache-i-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-i-

      - name: GitHub
        uses: 'selfagency/mastofeedbot@main'
        with:
          rss-feed: https://jewschool.com/feed
          api-endpoint: https://kibitz.cloud/api/v1/
          api-token: ${{ secrets.MASTODON_API_TOKEN }}
          cache-file: ${{ github.workspace }}/mastofeedbot/cache.json
