name: Jewschool.com
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  jewschool:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())

      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/mastofeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-

      - name: Jewschool.com
        uses: 'selfagency/mastofeedbot@main'
        with:
          rss-feed: https://feeds.feedburner.com/jewschool/feed
          api-endpoint: https://kibitz.cloud
          api-token: ${{ secrets.JEWSCHOOL_MASTO_TOKEN }}
          cache-file: ${{ github.workspace }}/mastofeedbot/cache.json
